version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: buget
      MYSQL_ROOT_PASSWORD: example